language: python
python:
- '2.7'
services:
  - redis-server
install:
- pip install -r requirements.txt --use-mirrors
script: bash scripts/integration_test
deploy:
  provider: heroku
  api_key:
    secure: TjyGL0+Dbogf4LnIMNNxLB/jnAo8uhQ7jxne8sDkNvVol7Qmj91OoGemj35oynH0jsvqeKK8yoHA9uh3J5qBs4NoNQIOea34lv4BxmujmfO7pI6ZyqHy7ZPVSRU1SUo4qExcHF+AYE8pxFNpEqISEQn9N6MTQYWYGrJOwqA26ik=
  app: doof
env:
  global:
  - secure: asHecjX0lfvVMfzOpGX0NX72afYrGZMFBjdDC5AOVuFGAQTQOKt/V5wR7/PbkQGcAXyVToqQA/jY5kEKXC1zl2m/2wpq01svLwq6hwhSG7U2NXjkvszZhfHAhrfhKbXfCFDtV+P1aCdX9Nr8//waLP2wTTKQJrnlb5lYhXwgrrA=
  - secure: EoQeD6BEGV91uVhuwkJZ7A9hV04mWlYKONrKn8tGWzaeOLzZ7WlA1oRhlR0EEtnmtVmHY84k5qXa90VIQ6JhD9KxyXK5G572SH8/VDteKUBJsfcICCSatjs9x/Bs8FB/B1maOQhsOaSi36a+ZTef5P1GHd1btFaXNVZsuWPKM0Y=
  - secure: jTNsLLbBaSWjejQns/zezY2LeN8sZOW6LC3x4gu/A8xhm3CfD/oVcP3OpqplQMMsVA+9U3Q9/25McDbc8g7BuggFLCoKjRdptkJwgQ+OjCCPijtogN3YQbq34zLp8HNz2Rr8deX04ekdS6p+P2BGx4AVBCmv2Ajwm3ocDaWjxak=
  - secure: uAV8gg3Bw3EBzGrOJcprgBSu1W++J4BHQvgXM3OKvey5YcCb22mFamCon32jCLNs8vOdL3gcpE2MTXAFeihatkILBiNCagEIASRL1GEqOFW+DS/2xf7qLahhKWrUew31Qim4hHZGIdONJFv+nIT9kewWw9MmQd/R/UwelAe6XEY=
  - secure: s0PIX86TyyLkuag5QJ9LavaJL6Th80Pt6SBPcDWJGMnFHcA6E3v+pX2YD1kXO/jnQOZO1pcS+nQRiCCYtk8OatB5p0iCxQOXPob0gnSP1Fxob02TTCdwf8/AS5Gr7nFFtowisOeaAcqtoK49K6yb3xt0rNnQYnp0vJ7AjVAdTzU=
  - secure: Pjz5DI8kxzk4EYhTqwBIr+2zoArEcOna0u9RjIrSEF3P1NKpHFpQt7uy/tiPPUWja/F7nSsf6BPJgO/AuI1ggLfXNQbBEhf3LYHYFIPckeKz5hUe3GiY4/sxNn0cLiTjoqjmBGrt6oWvgVQBxQ/jX79lzzba91OgK4nElHZpZkU=
