language: python
python:
- '2.7'
services:
- redis-server
install:
- pip install -r requirements.txt --use-mirrors
script: bash scripts/integration_test
deploy:
  provider: heroku
  api_key:
    secure: WY8L6il4T8dNhF5F2T/595CG1PYdY0C/LypuqQ2Fr2/8r//MjlcOa6CeuIyVXvAcS0Q9wgW3t3HlL1L9w4eYGxk+Of7GWcMtMhJZqOzuCbP5+KivexXDQYAhx5wLyWozBPDNUv64DCQW3ZxD1ZwTklgVGgbnkrNNORxoiwv0sNI=
  app: doof
env:
  global:
  - secure: p9TdN4wNxB4zSJBVGMvUbvbostu/TGfCKO7VS2DhqxeyoEXsfnNPy4uQ1oQgjWQ4e5nlDyVNKuYMA3BO5xx0kRqsyrk4ja+UatgSPsPbcaCXo/CIgTQB6c4aoUnNtZVFWgu/Zz/K3g89bk9AWVhXvNfpvywiBJBfi5P/g/GiQiA=
  - secure: sJl+MPAXrVOAjzwYbIAEPNgXHqhe76n4JjAbrkUhf4yBYPXmnE6EnFkyAJq1l+Ba/MZlMVJlrvzfx9oRAU4/lHVsITNfoOHDOncr+dKgpky9xPSmHOC5Oq3uJ8k3GMXYiIs9LsGIxa34z6MUZq+w6J3jb/R1x80AFFNJHGitnls=
  - secure: gpLw28DSmYYyPnTlydJ7BVdBTFXyfLa6dXVw2N382PIjT/6Juq9iDHIeKO3BBkp07zEBlF9aZ/JIDpDBhy+GcxCrrMamG9ukstpurDdcv2HqeE0GQV0oHzz8VLj2FO9/nFNoP3xw4lg2GP2VXPIWktbNPvoeKjKYRrf021OcH2o=
  - secure: RrmA1krtA0RH3ySiTxh6dujy6tMgx52eQHzG5k4UcN/vpzhuFn5IG1Y/OxA2IjZiro9T07s/OKWb5I9WLb/8hNo4sxKffDmBiWAXcijxuAxYzXtEzNhfmci0j02Vr2yG3s95tAQ8KrIivQrZQnFHWCPz2nYpCbOtezXO1gQyoKk=
  - secure: fgjhWu/Y4br3XjJ/FP6ho7r7dvIb5OoF1UxZbmTxsMP7nPHWL4dYtRNm2wOYzoGzRv6KQd5EMpcPVyRsADmICo+H+5Xy/iDmHo5iFbWeSQf3ArCjKGCkGVTYjPn2CW2Z2jVgyAjMIuOAEK0GjKcCbTJgS628dZMMd0UuM6o310c=
