#!/bin/bash

if [ -f "test_credentials" ]
then
    echo "Sourcing credentials from 'test_credentials'."
    source test_credentials
else
    echo "Using environment for credentials."
fi

# Simple "integration" test to see if the bot runs
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
cd $DIR
cd ..
./doof.py &
PID=$!
sleep 10
RUNNING=$(ps a | grep doof | grep -v grep | wc -l)
if [ ${RUNNING} -gt 0 ]; then
    kill $PID
    ps a | grep doof | grep -v grep | awk '{print $1}' | xargs kill -9
    exit 0;
else
    exit 1;
fi
